import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Stebin - UI/UX Designer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <section className={`${styles.hero}`}>
              <Image
                className={`${styles.heroImage}`}
                src="/sebhero.png"
                alt="Next.js Logo"
                width={100}
                height={100}
                priority
              />
              <div className={` ${styles.heroContent}`}>
                  <h1>Hello there, I'm <span className={`${styles.name}`}>Stebin Sebatine</span></h1>
                  <h2>I'm a <span className={`${styles.title}`}>UI/UX Designer</span> based in Melbourne</h2>
                  <h3>I love designing web & user interfaces and</h3> <h4>photography</h4>
              </div>

          </section>
      </main>

      <nav className="container">
        <div className="icon hov">
          <div className="img" aria-label="Randomly picked icon image holder" role="img"></div>
          <div className="text">Home</div>
        </div>
        <div className="icon hov">
          <div className="img" aria-label="Randomly picked icon image holder" role="img"></div>
          <div className="text">About</div>
        </div>
        <div className="icon hov">
          <div className="img" aria-label="Randomly picked icon image holder" role="img"></div>
          <div className="text">Work</div>
        </div>
        <div className="icon hov">
          <div className="img" aria-label="Randomly picked icon image holder" role="img"></div>
          <div className="text">Photography</div>
        </div>
        <div className="icon hov">
          <div className="img" aria-label="Randomly picked icon image holder" role="img"></div>
          <div className="text">Resume</div>
        </div>

      </nav>

    </>
  )
}
